### ISSUE TITLE
System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by v-jiaodi** [graemefoster/LockedDownChatBot#1]
**Describe the issue:**
When executing `azd up` according to [README.md](https://github.com/graemefoster/LockedDownChatBot#readme), the error is as follows:

![image](https://github.com/graemefoster/LockedDownChatBot/assets/80496810/da3a7882-6266-40fa-9a22-1a8d99c06e03)

**Repro Steps:**
```
gh repo clone graemefoster/LockedDownChatBot
cd LockedDownChatBot
azd up
```
**Environment:**
- OS: Windows desktop.

**Expected behavior:**
Run `azd up` can pass.

 @hemarina for notification.

**Comment by graemefoster** [comment]
Fixed - there was an expectation of some env variables being set. Have removed that expectation.
