### ISSUE TITLE
Use `azd init` instead of `gh repo clone` 

### ISSUE THREAD

**Issue by v-jiaodi** [graemefoster/LockedDownChatBot#2]
For azd templates, it is recommended to use `azd init` to initialize the project. At the same time, there is no need to pre install  `github CLI`.
![image](https://github.com/graemefoster/LockedDownChatBot/assets/80496810/7f4b0435-0423-4cab-888a-62ba5ca932f2)

**Suggestion:**
Update `gh repo clone graemefoster/LockedDownChatBot and cd LockedDownChatBot` to `azd init -t graemefoster/LockedDownChatBot`.

@hemarina for notification.

**Comment by graemefoster** [comment]
Done
