### ISSUE TITLE
Failed to create openai service

### ISSUE THREAD

**Issue by v-jiaodi** [graemefoster/LockedDownChatBot#3]
**Describe the issue:**
When run `azd up`,get error as follow:
<img width="619" alt="image" src="https://github.com/Azure/awesome-azd/assets/80496810/8170cdf7-9c50-40b5-a135-927b529b02cf">

**Repro Steps:**
```
azd init -t graemefoster/LockedDownChatBot

azd up
```
**Environment:**
 - OS: Windows desktop.
 - Azd version: azd version 1.1.0 (commit ea9cb12575734ee6a5f99c4d415c1a51d6f32d3e)
 
**Expected behavior:**
Run `azd up` can pass.

@graemefoster  for notification.

**Comment by graemefoster** [comment]
@v-jiaodi hmm do you have OpenAI enabled on your subscription? I don't think this is a problem with the template. I had to put in a request to get access to OpenAI.

**Comment by graemefoster** [comment]
@v-jiaodi - If you already have an OpenAI service then you can use the env variables as mentioned in the readme.md file, to link to an existing one rather than having the template create a new one.

**Comment by v-jiaodi** [comment]
> @v-jiaodi - If you already have an OpenAI service then you can use the env variables as mentioned in the readme.md file, to link to an existing one rather than having the template create a new one.

@graemefoster When change location from `eastus` to `eastus2`, running `azd up` can create openai service , but get new error as follow:
![image](https://github.com/graemefoster/LockedDownChatBot/assets/80496810/d2902f9f-2e3c-4573-b624-f58916aef645)

In addition, setting the location for creating openai to variable would be more user-friendly, rather than fixed to `eastus`.

**Comment by graemefoster** [comment]
@v-jiaodi this is fixed now - I saw it earlier when I had a smaller environment name. 

Apologies for the bug.

**Comment by graemefoster** [comment]
@v-jiaodi   I can push a fix to the location - problem I have is that open ai is only in a hand full of regions… if you allow any region, it would fail for 80% of them, so you would need to have a special location just for open ai :( 

happy to take advise on the best way to approach this…

should we have every template using open ai pick from a special enumeration and force an env var outside the standard location?

**Comment by graemefoster** [comment]
Fixed - you can more provide a location to override the default eastus via env
